CREATE TABLE `callingForms` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `firstName` varchar(255) COLLATE utf8_bin NOT NULL,
  `middleName` varchar(255) COLLATE utf8_bin NOT NULL,
  `lastName` varchar(255) COLLATE utf8_bin NOT NULL,
  `position` varchar(255) COLLATE utf8_bin NOT NULL,
  `currentPositionHolder` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `recommendedBy` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `recommendedDate` date DEFAULT NULL,
  `submittedBy` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `submittedDate` date DEFAULT NULL,
  `reason` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  `templeWorthy` tinyint(3) unsigned DEFAULT NULL,
  `wardId` int(10) unsigned DEFAULT NULL,
  `currentCalling` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `currentCallingStartDate` date DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `altPhone` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `spouse` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `spouseCurrentCalling` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `bishopConsulted` tinyint(3) unsigned DEFAULT NULL,
  `bishopConsultedDate` date DEFAULT NULL,
  `highCouncilRepConsulted` tinyint(3) unsigned DEFAULT NULL,
  `highCouncilRepConsultedDate` date DEFAULT NULL,
  `stakePresidencyApproval` tinyint(3) unsigned DEFAULT NULL,
  `stakePresidencyApprovalDate` date DEFAULT NULL,
  `highCouncilApproval` tinyint(3) unsigned DEFAULT NULL,
  `highCouncilApprovalDate` date DEFAULT NULL,
  `interviewed` tinyint(3) DEFAULT NULL,
  `interviewer` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `interviewDate` date DEFAULT NULL,
  `interviewResults` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  `interviewNotes` varchar(1024) COLLATE utf8_bin DEFAULT NULL,
  `incumbentReleased` tinyint(3) unsigned DEFAULT NULL,
  `incumbentReleaser` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `incumbentReleaseDate` date DEFAULT NULL,
  `sustained` tinyint(3) unsigned DEFAULT NULL,
  `sustainer` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sustainedDate` date DEFAULT NULL,
  `setApart` tinyint(3) unsigned DEFAULT NULL,
  `setApartBy` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `setApartDate` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `wards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
